name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}

      - name: Fetch tests branch
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "CI"
          git fetch origin tests
          git checkout tests -- test/
          git reset test/

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++

      - name: Build
        run: make all

      - name: Run tests
        run: |
          if [ -f "test/skip_list_test.cpp" ]; then
            make test
          else
            echo "Test files not found, skipping tests"
            exit 0
          fi