name: C++ CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make cmake libgtest-dev

      - name: Build and install GTest
        run: |
          cd /usr/src/googletest
          sudo cmake -B build -DCMAKE_BUILD_TYPE=Release
          sudo cmake --build build
          sudo cmake --install build

      - name: Run make
        run: make