name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare tests
        run: |
          git fetch origin tests
          git branch tests FETCH_HEAD
          git checkout tests -- test/
          git checkout -

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++

      - name: Build
        run: make all

      - name: Run tests
        run: |
          if [ -d "test" ]; then
            make test
          else
            echo "Warning: Test directory not found"
          fi