name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check for tests branch
        id: check-branch
        run: |
          if git ls-remote --exit-code --heads origin tests; then
            echo "tests_branch_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tests_branch_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Fetch tests (if branch exists)
        if: steps.check-branch.outputs.tests_branch_exists == 'true'
        run: |
          git fetch origin tests
          git checkout tests -- test/
          git reset -- test/

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ libgtest-dev cmake
          # Собираем и устанавливаем gtest
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/lib

      - name: Build
        run: make all

      - name: Run tests
        if: steps.check-branch.outputs.tests_branch_exists == 'true'
        run: make test