name: C++ CI

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ libgtest-dev

      - name: Compile tests
        run: |
          g++ -std=c++17 -pthread test/skip_list_test.cpp -o test_skip_list \
          -lgtest -lgtest_main -lpthread

      - name: Run tests
        run: ./test_skip_list