name: C++ CI (Makefile)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++

      - name: Build with Make
        run: |
          make all      # Или ваша конкретная цель сборки

      - name: Run tests
        run: |
          make test    # Если у вас есть тесты